version: "3"
services:
  mysql:
    image: mysql:5.6
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_DATABASE: lepus_db
      MYSQL_USER: lepus
      MYSQL_PASSWORD: lepuspassword
      MYSQL_ROOT_PASSWORD: mypassword
    command: --character-set-server=utf8
    volumes:
      - lepus-mysql:/var/lib/mysql
    expose:
      - "3306"
    restart: always

  redis:
    image: redis:5
    expose:
      - "6379"
    command: --requirepass "mypassword" --appendonly yes
    volumes:
      - lepus-redis:/data
    restart: always

  nsqlookupd:
    image: nsqio/nsq
    expose:
      - 4160:4160
      - 4161:4161
    command: /nsqlookupd
    restart: always

  nsqd:
    image: nsqio/nsq
    expose:
      - 4150:4150
      - 4151:4151
    volumes:
      - lepus-nsq:/data
    links:
      - "nsqlookupd:nsqlookupd"
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=nsqd
    depends_on:
      - nsqlookupd
    restart: always

  lepus:
    image: lepus
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Shanghai"
      mysql_user: lepus
      mysql_password: lepuspassword
      mysql_database: lepus_db
    volumes:
      - ./php/supervisor/piplin.conf:/etc/supervisor/conf.d/piplin.conf
      - ./src/:/var/www/piplin/
    links:
      - "mysql:lepus.mysql"
      - "redis:lepus.redis"
      - "nsqd:lepus.nsq"
    depends_on:
      - mysql
      - redis
      - nsqd
    restart: always

volumes:
  lepus-mysql:
  lepus-redis:
  lepus-nsq:
